# Generated by Django 5.1.4 on 2026-03-22 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActiveUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("token_key", models.CharField(db_index=True, max_length=100)),
                (
                    "user_email",
                    models.EmailField(blank=True, default="", max_length=254),
                ),
                ("user_name", models.CharField(blank=True, default="", max_length=100)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("platform", models.CharField(blank=True, default="", max_length=20)),
                (
                    "app_version",
                    models.CharField(blank=True, default="", max_length=20),
                ),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["-last_seen"],
            },
        ),
        migrations.CreateModel(
            name="DownloadEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("install_script", "Install Script"),
                            ("archive", "Archive Download"),
                        ],
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, default="")),
                ("platform", models.CharField(blank=True, default="", max_length=20)),
                ("arch", models.CharField(blank=True, default="", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InstallEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("started", "Started"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="started",
                        max_length=20,
                    ),
                ),
                ("version", models.CharField(blank=True, default="", max_length=20)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("platform", models.CharField(blank=True, default="", max_length=20)),
                ("arch", models.CharField(blank=True, default="", max_length=20)),
                (
                    "python_version",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                (
                    "node_version",
                    models.CharField(blank=True, default="", max_length=10),
                ),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
